#!/usr/bin/env python3
"""Generate NMI update figures and supplementary tables.

This script is intentionally data-light: the formal hypothesis tables are read
from the project CSV outputs, while the two new figure panels use the exact
aggregate values documented in experiments.md.
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TABLE_DIR = ROOT / "reports" / "tables"
SUPP_DIR = ROOT / "Supplementary Information"
FIG_DIR = ROOT / "Journal Images" / "Extended Data Figures"

BLUE = "#2166ac"
GREY = "#878787"
RED = "#b2182b"
GREEN = "#4daf4a"
ORANGE = "#ff7f00"


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    with path.open("w") as handle:
        handle.write("| " + " | ".join(fields) + " |\n")
        handle.write("| " + " | ".join(["---"] * len(fields)) + " |\n")
        for row in rows:
            handle.write("| " + " | ".join(str(row[field]) for field in fields) + " |\n")


def write_latex_table(
    path: Path,
    caption: str,
    label: str,
    rows: list[dict[str, str]],
    fields: list[tuple[str, str]],
    longtable: bool = True,
) -> None:
    env = "longtable" if longtable else "tabular"
    align = "lllllll" if len(fields) == 7 else "llllll"
    headers = [header for _, header in fields]
    with path.open("w") as handle:
        handle.write("% Auto-generated by code/scripts/generate_nmi_update_assets.py\n")
        handle.write("\\begin{" + env + "}{" + align + "}\n")
        handle.write("\\caption{" + caption + "}\\label{" + label + "}\\\\\n")
        handle.write("\\toprule\n")
        handle.write(" & ".join(latex_escape(header) for header in headers) + " \\\\\n")
        handle.write("\\midrule\n")
        handle.write("\\endfirsthead\n")
        handle.write("\\toprule\n")
        handle.write(" & ".join(latex_escape(header) for header in headers) + " \\\\\n")
        handle.write("\\midrule\n")
        handle.write("\\endhead\n")
        for row in rows:
            values = [latex_escape(row[key]) for key, _ in fields]
            handle.write(" & ".join(values) + " \\\\\n")
        handle.write("\\bottomrule\n")
        handle.write("\\end{" + env + "}\n")


def make_formal_test_tables() -> None:
    primary = read_csv(TABLE_DIR / "formal_hypothesis_tests_primary.csv")
    sham = read_csv(TABLE_DIR / "formal_hypothesis_tests_sham.csv")

    fields = [
        "Domain",
        "Task",
        "Model",
        "Drop flattened BA [95% CI]",
        "Raw p",
        "FDR p",
        "Significant",
    ]

    def clean_task(task: str) -> str:
        return task.replace("_", "-")

    primary_rows = [
        {
            "Domain": row["domain"],
            "Task": clean_task(row["task"]),
            "Model": row["model"],
            "Drop flattened BA [95% CI]": row["effect_95ci"],
            "Raw p": row["p_raw_display"],
            "FDR p": row["p_fdr_display"],
            "Significant": "Yes" if row["significant_fdr"] == "True" else "No",
        }
        for row in primary
    ]

    sham_rows = [
        {
            "Domain": row["domain"],
            "Task": clean_task(row["task"]),
            "Model": row["model"],
            "Sham drop BA [95% CI]": row["effect_95ci"],
            "Raw p": row["p_raw_display"],
            "FDR p": row["p_fdr_display"],
            "Significant": "Yes" if row["significant_fdr"] == "True" else "No",
        }
        for row in sham
    ]

    write_csv(SUPP_DIR / "supplementary_table_8a_formal_primary_tests.csv", primary_rows, fields)
    write_markdown(SUPP_DIR / "supplementary_table_8a_formal_primary_tests.md", primary_rows, fields)
    write_latex_table(
        SUPP_DIR / "supplementary_table_8a_formal_primary_tests.tex",
        "Formal primary flattening-drop tests with Benjamini--Hochberg FDR correction.",
        "tab:formal-primary-tests",
        primary_rows,
        [(field, field) for field in fields],
    )

    sham_fields = [
        "Domain",
        "Task",
        "Model",
        "Sham drop BA [95% CI]",
        "Raw p",
        "FDR p",
        "Significant",
    ]
    write_csv(SUPP_DIR / "supplementary_table_8b_formal_sham_tests.csv", sham_rows, sham_fields)
    write_markdown(SUPP_DIR / "supplementary_table_8b_formal_sham_tests.md", sham_rows, sham_fields)
    write_latex_table(
        SUPP_DIR / "supplementary_table_8b_formal_sham_tests.tex",
        "Formal sham-control tests with Benjamini--Hochberg FDR correction.",
        "tab:formal-sham-tests",
        sham_rows,
        [(field, field) for field in sham_fields],
    )

    combined_path = SUPP_DIR / "supplementary_table_8_formal_hypothesis_tests.tex"
    combined_path.write_text(
        "% Auto-generated by code/scripts/generate_nmi_update_assets.py\n"
        "\\textbf{Supplementary Table 8 | Formal hypothesis tests with BH-FDR correction.} "
        "One-sided bootstrap p-values are reported for primary flattening-drop tests; "
        "two-sided bootstrap p-values are reported for sham-control tests. "
        "Benjamini--Hochberg correction was applied separately to the 31 primary "
        "flattening comparisons and 28 sham comparisons at $q=0.05$.\n\n"
        "\\input{supplementary_table_8a_formal_primary_tests.tex}\n\n"
        "\\input{supplementary_table_8b_formal_sham_tests.tex}\n"
    )


def make_ptbxl_table() -> None:
    rows = [
        {
            "Cohort": "Unmatched",
            "Model": "PSD ridge",
            "Raw BA [95% CI]": "0.707 [0.687, 0.727]",
            "Aperiodic BA [95% CI]": "0.566 [0.543, 0.587]",
            "Flattened BA [95% CI]": "0.607 [0.586, 0.629]",
            "Flattening drop [95% CI]": "0.100 [0.079, 0.122]",
        },
        {
            "Cohort": "Unmatched",
            "Model": "ResNet1D-Wang",
            "Raw BA [95% CI]": "0.860 [0.844, 0.876]",
            "Aperiodic BA [95% CI]": "0.623 [0.605, 0.641]",
            "Flattened BA [95% CI]": "0.512 [0.501, 0.531]",
            "Flattening drop [95% CI]": "0.347 [0.331, 0.363]",
        },
        {
            "Cohort": "Unmatched",
            "Model": "Inception1D",
            "Raw BA [95% CI]": "0.866 [0.852, 0.879]",
            "Aperiodic BA [95% CI]": "0.578 [0.537, 0.640]",
            "Flattened BA [95% CI]": "0.508 [0.500, 0.517]",
            "Flattening drop [95% CI]": "0.358 [0.343, 0.373]",
        },
        {
            "Cohort": "Unmatched",
            "Model": "XResNet1D101",
            "Raw BA [95% CI]": "0.860 [0.846, 0.873]",
            "Aperiodic BA [95% CI]": "0.601 [0.502, 0.683]",
            "Flattened BA [95% CI]": "0.538 [0.506, 0.566]",
            "Flattening drop [95% CI]": "0.322 [0.291, 0.354]",
        },
        {
            "Cohort": "Age/sex matched",
            "Model": "PSD ridge",
            "Raw BA [95% CI]": "0.612 [0.586, 0.637]",
            "Aperiodic BA [95% CI]": "0.500 [0.500, 0.500]",
            "Flattened BA [95% CI]": "0.580 [0.559, 0.600]",
            "Flattening drop [95% CI]": "0.032 [0.009, 0.056]",
        },
        {
            "Cohort": "Age/sex matched",
            "Model": "ResNet1D-Wang",
            "Raw BA [95% CI]": "0.819 [0.799, 0.839]",
            "Aperiodic BA [95% CI]": "0.577 [0.529, 0.623]",
            "Flattened BA [95% CI]": "0.507 [0.501, 0.514]",
            "Flattening drop [95% CI]": "0.312 [0.293, 0.331]",
        },
        {
            "Cohort": "Age/sex matched",
            "Model": "Inception1D",
            "Raw BA [95% CI]": "0.830 [0.811, 0.848]",
            "Aperiodic BA [95% CI]": "0.542 [0.523, 0.566]",
            "Flattened BA [95% CI]": "0.519 [0.510, 0.529]",
            "Flattening drop [95% CI]": "0.311 [0.291, 0.330]",
        },
        {
            "Cohort": "Age/sex matched",
            "Model": "XResNet1D101",
            "Raw BA [95% CI]": "0.820 [0.801, 0.840]",
            "Aperiodic BA [95% CI]": "0.574 [0.535, 0.608]",
            "Flattened BA [95% CI]": "0.521 [0.510, 0.533]",
            "Flattening drop [95% CI]": "0.299 [0.279, 0.319]",
        },
    ]
    fields = list(rows[0].keys())
    write_csv(SUPP_DIR / "supplementary_table_9_ptbxl_ecg_results.csv", rows, fields)
    write_markdown(SUPP_DIR / "supplementary_table_9_ptbxl_ecg_results.md", rows, fields)
    write_latex_table(
        SUPP_DIR / "supplementary_table_9_ptbxl_ecg_results.tex",
        "PTB-XL ECG spectral audit numerical results.",
        "tab:ptbxl-ecg-results",
        rows,
        [(field, field) for field in fields],
    )


def make_tuab_temporal_table() -> None:
    rows = [
        {
            "Scenario": "Within early",
            "Recording era": "2009--2011",
            "Flattening drop [95% CI]": "0.118 [0.068, 0.165]",
            "Evaluation subjects": "137",
        },
        {
            "Scenario": "Within late",
            "Recording era": "2012--2013",
            "Flattening drop [95% CI]": "0.204 [0.153, 0.253]",
            "Evaluation subjects": "120",
        },
        {
            "Scenario": "Train early to eval late",
            "Recording era": "2009--2011 to 2012--2013",
            "Flattening drop [95% CI]": "0.146 [0.107, 0.184]",
            "Evaluation subjects": "120",
        },
        {
            "Scenario": "Train late to eval early",
            "Recording era": "2012--2013 to 2009--2011",
            "Flattening drop [95% CI]": "0.164 [0.105, 0.221]",
            "Evaluation subjects": "137",
        },
    ]
    fields = list(rows[0].keys())
    write_csv(SUPP_DIR / "supplementary_table_10_tuab_temporal_audit.csv", rows, fields)
    write_markdown(SUPP_DIR / "supplementary_table_10_tuab_temporal_audit.md", rows, fields)
    write_latex_table(
        SUPP_DIR / "supplementary_table_10_tuab_temporal_audit.tex",
        "TUAB temporal acquisition-proxy PSD audit.",
        "tab:tuab-temporal-audit",
        rows,
        [(field, field) for field in fields],
        longtable=False,
    )


def hex_to_rgb(color: str) -> tuple[float, float, float]:
    color = color.lstrip("#")
    return tuple(int(color[i : i + 2], 16) / 255 for i in (0, 2, 4))


def pdf_escape(text: object) -> str:
    return str(text).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


class SimplePDF:
    """Small vector-PDF helper for bar-chart style paper figures."""

    def __init__(self, width: float, height: float) -> None:
        self.width = width
        self.height = height
        self.ops: list[str] = []

    def stroke_color(self, color: str) -> None:
        r, g, b = hex_to_rgb(color)
        self.ops.append(f"{r:.3f} {g:.3f} {b:.3f} RG")

    def fill_color(self, color: str) -> None:
        r, g, b = hex_to_rgb(color)
        self.ops.append(f"{r:.3f} {g:.3f} {b:.3f} rg")

    def line(self, x1: float, y1: float, x2: float, y2: float, color: str = "#000000", width: float = 0.6, dash: bool = False) -> None:
        self.stroke_color(color)
        self.ops.append(f"{width:.2f} w")
        self.ops.append("[3 2] 0 d" if dash else "[] 0 d")
        self.ops.append(f"{x1:.2f} {y1:.2f} m {x2:.2f} {y2:.2f} l S")

    def rect(self, x: float, y: float, w: float, h: float, fill: str, stroke: str | None = None, width: float = 0.6) -> None:
        self.fill_color(fill)
        if stroke:
            self.stroke_color(stroke)
            self.ops.append(f"{width:.2f} w")
            self.ops.append(f"{x:.2f} {y:.2f} {w:.2f} {h:.2f} re B")
        else:
            self.ops.append(f"{x:.2f} {y:.2f} {w:.2f} {h:.2f} re f")

    def text(self, x: float, y: float, text: object, size: float = 8, color: str = "#000000", align: str = "left") -> None:
        self.fill_color(color)
        escaped = pdf_escape(text)
        width_est = len(str(text)) * size * 0.48
        if align == "center":
            x -= width_est / 2
        elif align == "right":
            x -= width_est
        self.ops.append(f"BT /F1 {size:.1f} Tf {x:.2f} {y:.2f} Td ({escaped}) Tj ET")

    def save(self, path: Path) -> None:
        content = "\n".join(self.ops).encode("latin-1", errors="replace")
        objects = [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            (
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {self.width:.2f} {self.height:.2f}] "
                f"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"
            ).encode(),
            b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
            b"<< /Length " + str(len(content)).encode() + b" >>\nstream\n" + content + b"\nendstream",
        ]
        chunks = [b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"]
        offsets = [0]
        for idx, obj in enumerate(objects, start=1):
            offsets.append(sum(len(chunk) for chunk in chunks))
            chunks.append(f"{idx} 0 obj\n".encode() + obj + b"\nendobj\n")
        xref_offset = sum(len(chunk) for chunk in chunks)
        chunks.append(f"xref\n0 {len(objects) + 1}\n".encode())
        chunks.append(b"0000000000 65535 f \n")
        for offset in offsets[1:]:
            chunks.append(f"{offset:010d} 00000 n \n".encode())
        chunks.append(
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode()
        )
        path.write_bytes(b"".join(chunks))


def ymap(value: float, bottom: float, top: float, ymax: float) -> float:
    return bottom + (value / ymax) * (top - bottom)


def draw_axes(pdf: SimplePDF, left: float, bottom: float, width: float, height: float, ymax: float, ylabel: str | None = None) -> None:
    pdf.line(left, bottom, left, bottom + height, width=0.6)
    pdf.line(left, bottom, left + width, bottom, width=0.6)
    for tick in [0, ymax / 2, ymax]:
        y = ymap(tick, bottom, bottom + height, ymax)
        pdf.line(left - 3, y, left, y, width=0.5)
        pdf.text(left - 5, y - 3, f"{tick:.2f}", size=6.5, align="right")
    if ylabel:
        pdf.text(left - 34, bottom + height + 8, ylabel, size=7)


def draw_bar_panel(
    pdf: SimplePDF,
    left: float,
    bottom: float,
    width: float,
    height: float,
    labels: list[str],
    values: list[float],
    lows: list[float],
    highs: list[float],
    colors: list[str],
    ymax: float,
    title: str,
    panel: str | None = None,
) -> None:
    if panel:
        pdf.text(left - 18, bottom + height + 20, panel, size=10)
    pdf.text(left + width / 2, bottom + height + 14, title, size=8, align="center")
    draw_axes(pdf, left, bottom, width, height, ymax, ylabel="Flattening drop (BA)")
    pdf.line(left, ymap(0, bottom, bottom + height, ymax), left + width, ymap(0, bottom, bottom + height, ymax), dash=True)
    slot = width / len(values)
    bar_w = slot * 0.56
    for i, value in enumerate(values):
        x = left + slot * i + (slot - bar_w) / 2
        y = ymap(value, bottom, bottom + height, ymax)
        pdf.rect(x, bottom, bar_w, y - bottom, fill=colors[i])
        xc = x + bar_w / 2
        lo = ymap(lows[i], bottom, bottom + height, ymax)
        hi = ymap(highs[i], bottom, bottom + height, ymax)
        pdf.line(xc, lo, xc, hi, width=0.7)
        pdf.line(xc - 3, lo, xc + 3, lo, width=0.7)
        pdf.line(xc - 3, hi, xc + 3, hi, width=0.7)
        for j, part in enumerate(labels[i].split("\n")):
            pdf.text(xc, bottom - 12 - j * 8, part, size=6.5, align="center")


def make_ecg_figure() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    pdf = SimplePDF(518.4, 169.2)
    draw_bar_panel(
        pdf,
        38,
        45,
        125,
        82,
        ["PSD\nridge", "ResNet1D-\nWang", "Inception1D", "XResNet\n1D101"],
        [0.100, 0.347, 0.358, 0.322],
        [0.079, 0.331, 0.343, 0.291],
        [0.122, 0.363, 0.373, 0.354],
        [GREY, BLUE, BLUE, BLUE],
        0.40,
        "Unmatched PTB-XL",
        "a",
    )

    left, bottom, width, height, ymax = 208, 45, 125, 82, 0.40
    pdf.text(left - 18, bottom + height + 20, "b", size=10)
    pdf.text(left + width / 2, bottom + height + 14, "Neural drops after matching", size=8, align="center")
    draw_axes(pdf, left, bottom, width, height, ymax, ylabel="Flattening drop (BA)")
    labels = ["ResNet1D-\nWang", "Inception1D", "XResNet\n1D101"]
    unmatched = [0.347, 0.358, 0.322]
    unmatched_lo = [0.331, 0.343, 0.291]
    unmatched_hi = [0.363, 0.373, 0.354]
    matched = [0.312, 0.311, 0.299]
    matched_lo = [0.293, 0.291, 0.279]
    matched_hi = [0.331, 0.330, 0.319]
    slot = width / len(labels)
    bar_w = slot * 0.28
    for i, label in enumerate(labels):
        center = left + slot * i + slot / 2
        for offset, value, lo, hi, color in [
            (-bar_w / 1.7, unmatched[i], unmatched_lo[i], unmatched_hi[i], BLUE),
            (bar_w / 1.7, matched[i], matched_lo[i], matched_hi[i], GREEN),
        ]:
            x = center + offset - bar_w / 2
            y = ymap(value, bottom, bottom + height, ymax)
            pdf.rect(x, bottom, bar_w, y - bottom, fill=color)
            xc = x + bar_w / 2
            ylo = ymap(lo, bottom, bottom + height, ymax)
            yhi = ymap(hi, bottom, bottom + height, ymax)
            pdf.line(xc, ylo, xc, yhi, width=0.7)
            pdf.line(xc - 3, ylo, xc + 3, ylo, width=0.7)
            pdf.line(xc - 3, yhi, xc + 3, yhi, width=0.7)
        for j, part in enumerate(label.split("\n")):
            pdf.text(center, bottom - 12 - j * 8, part, size=6.5, align="center")
    pdf.rect(left + 69, bottom + height - 4, 7, 5, fill=BLUE)
    pdf.text(left + 80, bottom + height - 4, "Unmatched", size=6.5)
    pdf.rect(left + 69, bottom + height - 14, 7, 5, fill=GREEN)
    pdf.text(left + 80, bottom + height - 14, "Age/sex matched", size=6.5)

    left, bottom, width, height = 381, 62, 94, 52
    pdf.text(left - 18, bottom + height + 37, "c", size=10)
    pdf.text(left + width / 2, bottom + height + 31, "ECG fit quality", size=8, align="center")
    pdf.line(left, bottom, left + width, bottom, width=0.6)
    pdf.line(left, bottom, left, bottom + height, width=0.6)
    pdf.text(left + width / 2, bottom - 22, "SpecParam R2", size=7, align="center")
    for tick in [0, 0.3, 0.6]:
        x = left + tick / 0.65 * width
        pdf.line(x, bottom - 3, x, bottom, width=0.5)
        pdf.text(x, bottom - 12, f"{tick:.1f}", size=6.5, align="center")
    q10, q25, q50, q75, q90 = 0.138, 0.198, 0.273, 0.356, 0.442
    qx = lambda value: left + value / 0.65 * width
    y = bottom + height / 2
    pdf.rect(qx(q10), y - 2, qx(q90) - qx(q10), 4, fill=GREY)
    pdf.rect(qx(q25), y - 5, qx(q75) - qx(q25), 10, fill=BLUE)
    pdf.rect(qx(q50) - 2, y - 2, 4, 4, fill=RED)
    pdf.text(qx(q50), y + 13, "median 0.273", size=6.5, align="center")
    pdf.text(qx(q10), y - 15, "10th", size=6, align="center")
    pdf.text(qx(q90), y - 15, "90th", size=6, align="center")

    pdf.save(FIG_DIR / "ed_fig9_ptbxl_ecg_spectral_audit.pdf")


def make_tuab_temporal_figure() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    pdf = SimplePDF(288, 165.6)
    draw_bar_panel(
        pdf,
        40,
        43,
        205,
        78,
        ["Within\nearly", "Within\nlate", "Train early\neval late", "Train late\neval early"],
        [0.118, 0.204, 0.146, 0.164],
        [0.068, 0.153, 0.107, 0.105],
        [0.165, 0.253, 0.184, 0.221],
        [BLUE, RED, ORANGE, GREEN],
        0.28,
        "TUAB temporal acquisition-proxy audit",
    )
    pdf.save(FIG_DIR / "ed_fig10_tuab_temporal_audit.pdf")


def main() -> None:
    SUPP_DIR.mkdir(parents=True, exist_ok=True)
    make_formal_test_tables()
    make_ptbxl_table()
    make_tuab_temporal_table()
    make_ecg_figure()
    make_tuab_temporal_figure()


if __name__ == "__main__":
    main()
